language: python
dist: trusty
python:
    - "2.7"
env:
    - DISPLAY=:99.0
before_install:
    - sh -e /etc/init.d/xvfb start
    - sudo apt-get update -qq
install: "python install.py"
script:
    - python ./omf/runAllTests.py omf