language: python
sudo: required
python:
  - "2.7"
env:
  - DISPLAY=:99.0
before_install:
  - sh -e /etc/init.d/xvfb start
  - apt-get update -qq
  - python install.py
  - export BOTO_CONFIG=/dev/null
install: "python setup.py develop"
script:
  - python ./omf/runAllTests.py omf