language: python
python:
  - "2.7"
env:
  - DISPLAY=:99.0
sudo: false
addons:
  apt:
    packages:
    - python-pip
    - git 
    - unixodbc-dev
    - libfreetype6-dev
    - pkg-config
    - python-dev
    - python-numpy
before_install:
  - sh -e /etc/init.d/xvfb start
  - mkdir -p var/lib/dpkg/updates
  - mkdir var/lib/dpkg/available
  - touch ./var/lib/dpkg/status
  - dpkg -i --force-not-root --root=. ./omf/solvers/gridlabd/gridlabd_3.1.0-2_amd64.deb
install: "python setup.py develop"
script:
  - python ./omf/runAllTests.py ./omf/
