language: python
sudo: required
python:
  - "2.7"
addons:
  apt:
    update: true
env:
  - DISPLAY=:99.0
services:
  - xvfb
before_install:
  - python install.py
  - export BOTO_CONFIG=/dev/null
install: "python setup.py develop"
script:
  - python ./omf/runAllTests.py omf
