# FYI, you can validate this file here: https://config.travis-ci.com/explore
os:
  - osx
  - linux
language: generic
dist: bionic
addons:
  apt:
    update: true
env:
  - DISPLAY=:99.0
services:
  - xvfb
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install python3; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then apt-get install python3; fi
  - python3 install.py
  - export BOTO_CONFIG=/dev/null
install: "python3 setup.py develop"
script:
  - python3 ./omf/runAllTests.py omf