# FYI, you can validate this file here: https://config.travis-ci.com/explore
os: linux
dist: bionic
language: python
python:
  - "3.6"
addons:
  apt:
    update: true
env:
  - DISPLAY=:99.0
services:
  - xvfb
before_install:
  - python3 install.py
  - export BOTO_CONFIG=/dev/null
install: "python3 setup.py develop"
script:
  - python3 ./omf/runAllTests.py omf