language: python
python:
  - "2.7"
env:
  - DISPLAY=:99.0
sudo: false
addons:
  apt:
    packages:
    - python-pip
    - git 
    - unixodbc-dev
    - libfreetype6-dev
    - pkg-config
    - python-dev
    - python-numpy
    - alien
before_install:
  - sh -e /etc/init.d/xvfb start
  - cd omf/solvers/gridlabd
  - alien gridlabd-3.1.0-1.x86_64.rpm
  - dpkg -i --force-not-root --root=$HOME gridlabd_3.1.0-2_amd64.deb
  - cd ~/omf
install: "python setup.py develop"
script:
  - python ~/omf/runAllTests.py omf
