# FYI, you can validate this file here: https://config.travis-ci.com/explore
os:
  - osx
  - linux
  - windows
jobs:
  allow_failures:
    - os: osx
    - os: windows
language: generic
dist: bionic
addons:
  apt:
    update: true
env:
  - DISPLAY=:99.0
services:
  - xvfb
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -y install python3; sudo apt-get -y install python3-setuptools; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install python3; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then cmd.exe //c "RefreshEnv.cmd"; fi  
  - export BOTO_CONFIG=/dev/null
install: "python3 install.py"
script:
  - python3 ./omf/runAllTests.py omf